export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";
export const SET_SIDE_BAR_OPEN = "SET_SIDE_BAR_OPEN";
export const SET_SIDE_BAR_CLOSED = "SET_SIDE_BAR_CLOSED";

