export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";
export const SET_SIDE_BAR_OPEN = "SET_SIDE_BAR_OPEN";
export const SET_SIDE_BAR_CLOSED = "SET_SIDE_BAR_CLOSED";

export const FETCH_SEARCH_RESULTS_STARTED = "SET_SEARCH_RESULTS_STARTED";
export const FETCH_SEARCH_RESULTS_SUCCESS = "SET_SEARCH_RESULTS_SUCCESS";
export const FETCH_SEARCH_RESULTS_FAILED = "SET_SEARCH_RESULTS_FAILED";
export const FETCH_SEARCH_RESULTS_ENDED = "SET_SEARCH_RESULTS_ENDED";